module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#59BBAF',
        girl: '#E0195B',
        third: '#F8A41D',
        sec: '#202A5A',
        // Ecosystem
        'ecosystem-light': '#EEF8F7',
        'ecosystem-hover': '#E6F5F3',
        'ecosystem-active': '#CCEAE6',
        'ecosystem-normal': '#59BBAF',
        'ecosystem-dark': '#438C83',
        'ecosystem-darker': '#1F413D',
        // Male
        'male-light': '#E9EAEF',
        'male-hover': '#DEDFE6',
        'male-active': '#BABDCC',
        'male-normal': '#202A5A',
        'male-dark': '#182044',
        'male-darker': '#0B0F1F',
        // Female
        'female-light': '#FCE8EF',
        'female-hover': '#FADDE6',
        'female-active': '#F5B8CC',
        'female-normal': '#E0195B',
        'female-dark': '#A81344',
        'female-darker': '#4E0920',
        // College
        'college-light': '#FEF6E8',
        'college-hover': '#FEF1DD',
        'college-active': '#FDE3B9',
        'college-normal': '#F8A41D',
        'college-dark': '#BA7B16',
        'college-darker': '#57390A',
        // Club
        'club-light': '#F0EAF4',
        'club-hover': '#E8E0EE',
        'club-active': '#CFBEDD',
        'club-normal': '#652D90',
        'club-dark': '#4C226C',
        'club-darker': '#231032',
        // Ink / Text
        ink: {
          light: '#EAEAE9',
          normal: '#292827',
          dark: '#1F1E1D',
          darker: '#0E0E0E',
        },
      },
      fontFamily: {
        sans: ['IRANSansX', 'Montserrat', 'sans-serif'],
      },
      fontSize: {
        xs: ['10px', '15px'],
        sm: ['13px', '19.5px'],
        base: ['16px', '24px'],
        md: ['20px', '30px'],
        lg: ['25px', '37.5px'],
        xl: ['39px', '58.5px'],
        '2xl': ['49px', '73.5px'],
        '3xl': ['61px', '91.5px'],
      },
      borderRadius: {
        xs: '5px',
        sm: '8px',
        md: '12px',
        lg: '17px',
        xl: '24px',
        '2xl': '34px',
        pill: '40px',
      },
      boxShadow: {
        ecosystem: '2.75px 2.75px 0 #59BBAF',
        male: '2.75px 2.75px 0 #202A5A',
        female: '2.75px 2.75px 0 #E0195B',
        college: '2.75px 2.75px 0 #F8A41D',
        club: '2.75px 2.75px 0 #652D90',
        neutral: '2.75px 2.75px 0 #292827',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '12': '48px',
        '16': '64px',
      },
    },
  },
  plugins: [],
}