// src/lib/fallback/blog.js
// دیتای fallback برای سکشن بلاگ — همون پست‌های هاردکد فعلی
// هر پست به یک «پرسونا» تعلق داره: اکوسیستم / هنرجویان / دخترها / کالج / کلوپ
const fallbackBlogs = [
  // ─── اکوسیستم (teal) ───
  {
    id: "eco-1",
    slug: "ساخت-پروژه-اول-از-ایده-تا-اجرا",
    persona: "eco",
    icon: "🚀",
    tag: "راهنما",
    title: "ساخت پروژه‌ی اول؛ از ایده تا اجرا",
    body: "چطور یه پروژه‌ی واقعی رو از صفر شروع کنیم و تا انتها با انگیزه پیش ببریمش.",
    date: "بهار ۱۴۰۵",
    readTime: "۸ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "eco-2",
    slug: "اکوسیستم-یعنی-چه-نگاهی-به-شبکه-۱۲۰۰-نفری-رکاد",
    persona: "eco",
    icon: "🌍",
    tag: "گزارش",
    title: "اکوسیستم یعنی چه؟ نگاهی به شبکه‌ی ۱۲۰۰ نفری رکاد",
    body: "چرا از یک اکوسیستم زنده حرف می‌زنیم و نه فقط یک هنرستان؛ از کافه تا رویدادها.",
    date: "شهریور ۱۴۰۵",
    readTime: "۶ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },

  // ─── هنرجویان (navy) ───
  {
    id: "male-1",
    slug: "چطور-برای-اولین-بار-وارد-بازار-کار-شی",
    persona: "male",
    icon: "💼",
    title: "چطور برای اولین‌بار وارد بازار کار شی؟",
    body: "قدم‌به‌قدم با تجربه‌ی فارغ‌التحصیلای رکاد که رزومه‌شون رو ساختن و اولین قرارداد کاریشون رو گرفتن.",
    date: "تابستان ۱۴۰۵",
    readTime: "۹ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "male-2",
    slug: "استعدادسنجی-اولین-قدم-مسیر-شخصی-سازی-شده",
    persona: "male",
    icon: "🧭",
    tag: "ویژه",
    title: "استعدادسنجی؛ اولین قدم مسیر شخصی‌سازی‌شده",
    body: "چرا رکاد قبل از شروع هر چیزی، اول می‌شینه پای حرفت تا مسیر رشدت رو دقیق طراحی کنه.",
    date: "بهار ۱۴۰۵",
    readTime: "۵ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "male-3",
    slug: "مهارت-هایی-که-هر-هنرجو-قبل-از-فارغ-التحصیلی-یاد-بگیرد",
    persona: "male",
    icon: "🛠️",
    title: "مهارت‌هایی که هر هنرجو باید قبل از فارغ‌التحصیلی یاد بگیره",
    body: "لیستی از مهارت‌های عملی که تفاوت رزومه‌ی قوی و ضعیف رو مشخص می‌کنه.",
    date: "زمستان ۱۴۰۴",
    readTime: "۱۰ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },

  // ─── دخترها (magenta) ───
  {
    id: "female-1",
    slug: "وقتی-از-پزشکی-به-محصول-سازی-رسیدم",
    persona: "female",
    icon: "🌸",
    tag: "داستان",
    title: "وقتی از پزشکی به محصول‌سازی رسیدم",
    body: "داستان تغییر مسیر یک هنرجو که از مسیر همیشگی، به دنیای ساخت محصول رسید.",
    date: "شهریور ۱۴۰۵",
    readTime: "۷ دقیقه",
    author: "پریسا صادقی",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "female-2",
    slug: "mvp-۴۸-ساعته-از-ایده-تا-کاربر-اول",
    persona: "female",
    icon: "⚡",
    title: "MVP ۴۸ ساعته؛ از ایده تا کاربر اول",
    body: "راهنمای عملی برای اولین محصول‌سازی سریع؛ بدون خستگی و با تمرکز روی مهم‌ترین چیز.",
    date: "مرداد ۱۴۰۵",
    readTime: "۸ دقیقه",
    author: "مهسا رضایی",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "female-3",
    slug: "شش-سوالی-که-هنرجوها-همیشه-از-منتورها-می-پرسند",
    persona: "female",
    icon: "💬",
    title: "شش سوالی که هنرجوها همیشه از منتورها می‌پرسند",
    body: "و پاسخ‌های صادقانه‌ای که همیشه هم دلنشین نیست.",
    date: "مرداد ۱۴۰۵",
    readTime: "۵ دقیقه",
    author: "زهرا اسدی",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },

  // ─── کالج (orange) ───
  {
    id: "college-1",
    slug: "چطور-برای-فرزندمون-رشته-هنرستان-رو-انتخاب-کنیم",
    persona: "college",
    icon: "🎓",
    tag: "راهنما",
    title: "چطور برای فرزندمون رشته‌ی هنرستان رو انتخاب کنیم؟",
    body: "یه راهنمای عملی برای والدین که می‌خوان بهترین تصمیم رو برای آینده‌ی تحصیلی فرزندشون بگیرن.",
    date: "تابستان ۱۴۰۵",
    readTime: "۶ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "college-2",
    slug: "نقش-والدین-در-انتخاب-مسیر-شغلی-فرزند",
    persona: "college",
    icon: "🏡",
    title: "نقش والدین در انتخاب مسیر شغلی فرزند",
    body: "چه‌جوری بدون فشار زیاد، کنار فرزندمون باشیم تا خودش مسیرش رو پیدا کنه.",
    date: "زمستان ۱۴۰۴",
    readTime: "۷ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "college-3",
    slug: "دانشگاه-یا-هنرستان-یک-مقایسه-صادقانه",
    persona: "college",
    icon: "⚖️",
    tag: "مقایسه",
    title: "دانشگاه یا هنرستان؟ یک مقایسه‌ی صادقانه",
    body: "هر کدام از این دو مسیر برای چه تیپ آدمی مناسب‌تر است؛ بدون تعصب، فقط داستان واقعی.",
    date: "مرداد ۱۴۰۵",
    readTime: "۱۱ دقیقه",
    author: "نازنین مقدم",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },

  // ─── کلوپ (purple) ───
  {
    id: "club-1",
    slug: "داخل-کلوپ-ai-درگیر-با-آینده",
    persona: "club",
    icon: "🤖",
    tag: "جدید",
    title: "داخل کلوپ AI؛ درگیر با آینده",
    body: "هفته‌ای یک ورک‌شاپ، ماهی یک پروژه‌ی گروهی؛ گزارش اولین فصل کلوپ هوش مصنوعی رکاد.",
    date: "شهریور ۱۴۰۵",
    readTime: "۶ دقیقه",
    author: "آرش کاظمی",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "club-2",
    slug: "کلوپ-محصول-چطور-بحث-های-عمیق-داشته-باشیم",
    persona: "club",
    icon: "🧩",
    title: "کلوپ محصول: چطور بحث‌های عمیق داشته باشیم",
    body: "قواعد نانوشته‌ی جلسات کلوپ محصول رکاد؛ از نقد سازنده تا تصمیم گروهی.",
    date: "شهریور ۱۴۰۵",
    readTime: "۴ دقیقه",
    author: "هدیه رضوی",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
  {
    id: "club-3",
    slug: "۱۲-کلوپ-فعال-رکاد-کدام-یکی-جای-توست",
    persona: "club",
    icon: "🎯",
    tag: "گزارش",
    title: "۱۲ کلوپ فعال رکاد؛ کدام یکی جای توئه؟",
    body: "راهنمای انتخاب کلوپ بر اساس علاقه‌ی حرفه‌ای؛ از AI و محصول تا طراحی و پادکست.",
    date: "مرداد ۱۴۰۵",
    readTime: "۸ دقیقه",
    author: "تیم رکاد",
    image: "/assets/home/Blogs/blog-card-cover.png",
  },
];

export default fallbackBlogs;
